### ISSUE TITLE
Don't update indexes if index values have not changed

### ISSUE THREAD

**Issue by jonahcohen** [MySQLOnRocksDB/mysql-5.6#1]
Currently, ha_rocksdb::update_row() updates all indexes, even those who do not have a single changed column. We should update only those whose values were not changed.

A question: are there any rocksdb status counters that could be used to observe this?

**Comment by spetrunia** [comment]
There are two ways to detect that the columns haven't changed:
- Look at table->write_set and find which columns are written.  If some index doesn't have any columns that are written, it doesn't need to be updated
  *\* We don't need to make the check for every row, it is sufficient to do it per-query (todo is it the same as per-query or different?)
  *\* Need to run a few examples to check that SQL layer indeed sets table->write_set to those columns that are updated
- Right before issuing rocksdb->Put()/rocksdb->Delete() calls, check if we're going to write the same value as the one that's already there.

**Comment by yoshinorim** [comment]
If it works as expected, I like the first approach.

**Comment by spetrunia** [comment]
Implemented the first approach and committed here: https://reviews.facebook.net/D33471
