### ISSUE TITLE
Include RocksDB utility tools into MySQL binary

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#102]
ldb and sst_dump are at least needed for day-to-day production engineering work.

**Comment by maykov** [comment]
manifest dump would be useful too

**Comment by siying** [comment]
manfiest dump is an option of ldb.

**Comment by hermanlee** [comment]
ldb support is there, but there is currently a rocksdb task for enhancing ldb to support multiple column families.

**Comment by maykov** [comment]
This task is about putting these tools into RPM
