### ISSUE TITLE
support information_schema.table_statistics for RocksDB

### ISSUE THREAD

**Issue by jonahcohen** [MySQLOnRocksDB/mysql-5.6#13]
From @mdcallag:

I think this depends on basic support for IS.table_statistics getting ported to WebScaleSQL

**Comment by mdcallag** [comment]
Support is there. This can be done in pieces. Start by adding support to count rows read, fetched, inserted, updated, deleted.

**Comment by mdcallag** [comment]
Other parts include:
- read IO latency for user threads
- bytes written for user threads, but I am not sure there is a column for this in table_stats today

By "user threads" I mean threads that run user commands, not background threads.
