### ISSUE TITLE
mysqldump supporting RocksDB

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#24]
Now we have CONSISTENT SNAPSHOT in RocksDB, it's time to make mysqldump work for RocksDB.
At least two features are needed.
- START TRANSACTION WITH CONSISTENT ROCKSDB SNAPSHOT instead of INNODB SNAPSHOT. This can be done by either passing an option (i.e. --rocksdb) or by detecting if there are RocksDB tables.
- Adding an option to take dump by descending order -- adding an option --order-by-primary-desc then taking backup by descending order. This is efficient if primary key is reverse order.

**Comment by mdcallag** [comment]
Is the descending order option there to support desc order keys?
What about a key like (a asc, b desc, c asc, d desc)?
Doesn't MySQL ignore "desc" in DDL, see http://mysqlha.blogspot.com/2009/01/parsed-but-ignored.html?

**Comment by yoshinorim** [comment]
It won't support mixed order. All ASC or all DESC.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D32553
