### ISSUE TITLE
Bloom filters and column families

### ISSUE THREAD

**Issue by jonahcohen** [MySQLOnRocksDB/mysql-5.6#3]
From @mdcallag:

I assume we will put many indexes in one column family as column family per index doesn't scale to a large number of indexes. When that is done we need a method for specifying the index columns that will be used in the column family. This assumes that we can use bloom filters on a prefix of the index key and that the format of an index key within RockDB is:
...

In that case the options are:
1) no bloom filter
2) bloom filter on index ID
3) bloom filter on index ID, index column 1, ..., index column N-1>
4) bloom filter on index ID, index column 1, ..., index column N>

Note that

2) and 3) above are on a prefix of the visible index columns
2), 3), and 4) require all indexes in the column family to have a common prefix in columns
This requires much more discussion.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D32607
