### ISSUE TITLE
Address the TODO comment on Table_ddl_manager::put

### ISSUE THREAD

**Issue by maykov** [MySQLOnRocksDB/mysql-5.6#50]
This function modifies ddl_hash and index_num_to_keydef.
However, these changes need to be reversed if dict_manager.commit fails
See the discussion here: https://reviews.facebook.net/D35925#inline-259167

**Comment by yoshinorim** [comment]
@maykov  Now MyRocks always aborts if dict_manager.commit() fails. Do we still need to fix this?
