### ISSUE TITLE
Shutdown is too slow

### ISSUE THREAD

**Issue by mdcallag** [MySQLOnRocksDB/mysql-5.6#59]
The problem is the time required for RocksDB to call free on each block in the block cache. Sample stack traces during a slow shutdown are at https://gist.github.com/mdcallag/5ce2d163234ba8cc3bb0

By "too slow" I mean it takes ~30 seconds for RocksDB to shutdown when the block cache has ~15G of data

This might be fixed via "cache_->DisownData();" and see https://reviews.facebook.net/D34977

**Comment by maykov** [comment]
Let me know if it still slow.

**Comment by mdcallag** [comment]
Still too slow. See https://gist.github.com/mdcallag/77f33bb27c7e4da8ff2c

On Tue, Apr 28, 2015 at 2:23 PM, Alexey Maykov notifications@github.com
wrote:

> Let me know if it still slow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MySQLOnRocksDB/mysql-5.6/issues/59#issuecomment-97211721
> .

## 

Mark Callaghan
mdcallag@gmail.com

**Comment by maykov** [comment]
It looks like I added disowning for the default column family LRU but not for the rest.

**Comment by maykov** [comment]
Did you try with the per column family setting for the cache size? If so, this results in a creation of a separate lru cache for such families which we do not have an access to. Would you retry without that option? It is fine to provide the rocksdb_block_cache_size global option.

**Comment by mdcallag** [comment]
Yes, shutdown is fast now.

On Wed, Apr 29, 2015 at 4:28 PM, Alexey Maykov notifications@github.com
wrote:

> Did you try with the per column family setting for the cache size? If so,
> this results in a creation of a separate lru cache for such families which
> we do not have an access to. Would you retry without that option? It is
> fine to provide the rocksdb_block_cache_size global option.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MySQLOnRocksDB/mysql-5.6/issues/59#issuecomment-97613585
> .

## 

Mark Callaghan
mdcallag@gmail.com
