### ISSUE TITLE
Make rocksdb_datadir configurable

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#62]
Currently sst files are stored under $datadir/rocksdb and it's hard coded as 'std::string rocksdb_db_name=  "./rocksdb"'. This needs to be configurable.

**Comment by maykov** [comment]
I'm sending the diff to change the directory name to .rocksdb. Right now, this directory shows as the database called rocksdb when doing 'show databases'. It causes a bunch of tests to fail. Whatever we do, we should add a dot to the beginning of the name.

**Comment by maykov** [comment]
For documentation, here is where mysql scans the directory to get a list of databases: https://github.com/MySQLOnRocksDB/mysql-5.6/blob/webscalesql-5.6.23.71/sql/sql_show.cc#L3258
