### ISSUE TITLE
Make some options dynamically configurable

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#74]
Some options like rocksdb_bytes_per_sync should be configurable dynamically.

**Comment by jkedgar** [comment]
Does this mean that you want a global variable in MyRocks so that you can configure this option by using "Set rocksdb_bytes_per_sync = <value>"?

What other options should be this way?

**Comment by yoshinorim** [comment]
I'd like to start from dynamically configurable DB options. Static options such as wal_dir, rocksdb_data_dir are not targets. For CF/Table options, I think we need more discussions.

**Comment by jkedgar** [comment]
Is there a list of dynamically configurable options?

**Comment by yoshinorim** [comment]
^^ @siying @rven1

**Comment by siying** [comment]
Search options.h and all dynamic configurable options will write in comments "dynamic changeable".

**Comment by jkedgar** [comment]
The SetOptions() method appears to operate on a column family - the default column family if no column family is specified.  Do I need to iterate through all the column families when an option is set via MySQL or do I just set it for the default column family?

The bytes_per_sync setting does not appear to be dynamically configurable.  It is not listed as such in options.h and doesn't show up in util/options_helper.cc.  Am I missing something?
