### ISSUE TITLE
Export more perf_context and iostats_context

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#79]
Recently RocksDB added more status counters -- https://reviews.facebook.net/D39177
We need to export these stats into information_schema.

**Comment by yoshinorim** [comment]
And some other status counters, such as rocksdb.db.mutex.wait.micros.

**Comment by jtuple** [comment]
Added several additional metrics in commit d9eb6ecfb0dcba70cb868c096c17483bfd7ea59d. Not sure what other metrics we should export. Is there any reason we shouldn't just export all `pertf_context` and `iostats_context` stats?

**Comment by yoshinorim** [comment]
@jtuple You're right, we should just export all *_context stats. We haven't found a way to keep track of RocksDB side changes (RocksDB added some stats after we initially supported perf_context).

**Comment by jkedgar** [comment]
Just to be clear...  You want _all_ the values in perf_context.h (currently a total of 34) and iostats_context.h (currently a total of 9) to show up in information_schema.rocksdb_perf_context_global.  Correct?

**Comment by yoshinorim** [comment]
Yes.

**Comment by jkedgar** [comment]
Closed with https://reviews.facebook.net/D46437
