### ISSUE TITLE
Create information_schema.rocksdb_datadic to print data dictionary

### ISSUE THREAD

**Issue by yoshinorim** [MySQLOnRocksDB/mysql-5.6#83]
This is rather for debugging purposes, but printing data dictionary via information_schema is often very useful.

**Comment by hermanlee** [comment]
We have support for printing out the index numbers and tables/databases they belong to in information_schema.rocksdb_ddl, but other parts of the data dictionary need to be added (such as binlog numbers, column family indexes, etc.).

**Comment by yhchiang** [comment]
In case this is not something urgent, I would like to try this out :)

First of all, can I know whether `storage/rocksdb/rdb_i_s.cc` is the right file to begin with?  I'm not familiar with the mysql code base.

**Comment by hermanlee** [comment]
Yes, rdb_i_s.cc is the right place to start. It has the basic structure for creating information schema tables. The table would need to retrieve the contents of the data dictionary and convert them into the appropriate table format and return it.
